var ingredients = [
    "almond",
    "apple",
    "asafoetida",
    "asparagus",
    "baking powder",
    "baking soda",
    "banana",
    "bean",
    "beef",
    "beet",
    "bell pepper",
    "berry",
    "bhatura",
    "black pepper",
    "blueberry",
    "bread",
    "broccoli",
    "brussels sprout",
    "butter",
    "cabbage",
    "carrot",
    "cashew",
    "cauliflower",
    "celery",
    "cheese",
    "chickpea",
    "cherry",
    "chicken",
    "corn",
    "cranberry",
    "cucumber",
    "curry leaf",
    "eggplant",
    "egg",
    "fish",
    "flour",
    "garlic",
    "ginger",
    "ghee",
    "grain",
    "grape",
    "green bean",
    "spice",
    "herb",
    "hot pepper",
    "hot sauce",
    "pepper",
    "cardamom",
    "chilli",
    "cinnamon",
    "coriander",
    "cumin",
    "kale",
    "ketchup",
    "kiwi",
    "leek",
    "lentil",
    "lettuce",
    "lemon",
    "lemongrass",
    "lime",
    "mango",
    "marinara sauce",
    "microgreen",
    "milk",
    "mushroom",
    "mustard",
    "mustard seed",
    "naan",
    "nutmeg",
    "oil",
    "onion",
    "orange",
    "patty",
    "pasta",
    "paneer",
    "peach",
    "peanut",
    "pepperoni",
    "pear",
    "pea",
    "pineapple",
    "pork",
    "potato",
    "pumpkin",
    "radish",
    "ranch",
    "rhubarb",
    "rice",
    "roti",
    "salmon",
    "salt",
    "saffron",
    "spinach",
    "strawberry",
    "sugar",
    "squash",
    "sweet potato",
    "tofu",
    "tomato",
    "tuna",
    "turkey",
    "turmeric",
    "turnpis",
    "vanilla",
    "water",
    "watermelon",
    "wheat",
    "whole grain",
    "yogurt"
]